# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'StoreSystemInterfaceytiffI.ui'
##
## Created by: Qt User Interface Compiler version 6.6.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QFrame, QHeaderView,
    QLabel, QLineEdit, QMainWindow, QPushButton,
    QSizePolicy, QStackedWidget, QTableWidget, QTableWidgetItem,
    QWidget)
import res_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1131, 567)
        self.centralwidget = QWidget(MainWindow.centralWidget())
        self.centralwidget.setObjectName(u"centralwidget")
        self.LoginStackedWidget = QStackedWidget(self.centralwidget)
        self.LoginStackedWidget.setObjectName(u"LoginStackedWidget")
        self.LoginStackedWidget.setGeometry(QRect(0, 0, 1131, 571))
        self.LoginStackedWidget.setStyleSheet(u"QPushButton#pushButton{\n"
"	background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0, stop:0 rgba(11, 131, 120, 219), stop:1 rgba(85, 98, 112, 226));\n"
"	color:rgba(255, 255, 255, 210);\n"
"	border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton#pushButton:hover{\n"
"	background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0, stop:0 rgba(11, 131, 120, 219), stop:1 rgba(85, 98, 112, 226));\n"
"}\n"
"\n"
"QPushButton#pushButton:pressed{\n"
"	padding-left:5px;\n"
"	padding-top:5px;\n"
"	background-color:rgba(150, 123, 111, 255);\n"
"}\n"
"")
        self.LoginPage = QWidget()
        self.LoginPage.setObjectName(u"LoginPage")
        self.label_30 = QLabel(self.LoginPage)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(390, 90, 621, 391))
        self.label_30.setStyleSheet(u"border-image: url(:/gif /gifsample.gif);\n"
"border-top-right-radius: 50px;\n"
"border-bottom-right-radius: 50px;")
        self.label_31 = QLabel(self.LoginPage)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(390, 90, 621, 391))
        self.label_31.setStyleSheet(u"background-color:rgba(0, 0, 0, 80);\n"
"border-top-right-radius: 50px;\n"
"border-bottom-right-radius: 50px;")
        self.label_32 = QLabel(self.LoginPage)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(120, 90, 321, 391))
        self.label_32.setStyleSheet(u"background-color:rgba(255, 255, 255, 255);\n"
"border-top-left-radius: 50px;\n"
"border-bottom-left-radius: 50px;")
        self.label_33 = QLabel(self.LoginPage)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(240, 140, 100, 40))
        font = QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.label_33.setFont(font)
        self.label_33.setStyleSheet(u"color:rgba(0, 0, 0, 200);")
        self.lineEdit = QLineEdit(self.LoginPage)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(170, 210, 221, 40))
        font1 = QFont()
        font1.setPointSize(10)
        self.lineEdit.setFont(font1)
        self.lineEdit.setStyleSheet(u"background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46, 82, 101, 200);\n"
"color:rgba(0, 0, 0, 240);\n"
"padding-bottom: 7px")
        self.lineEdit_2 = QLineEdit(self.LoginPage)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(170, 260, 221, 40))
        self.lineEdit_2.setFont(font1)
        self.lineEdit_2.setStyleSheet(u"background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46, 82, 101, 200);\n"
"color:rgba(0, 0, 0, 240);\n"
"padding-bottom: 7px")
        self.lineEdit_2.setEchoMode(QLineEdit.Password)
        self.pushButton = QPushButton(self.LoginPage)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(170, 350, 221, 40))
        font2 = QFont()
        font2.setPointSize(11)
        font2.setBold(True)
        self.pushButton.setFont(font2)
        self.LoginStackedWidget.addWidget(self.LoginPage)
        self.MainWidget = QWidget()
        self.MainWidget.setObjectName(u"MainWidget")
        self.MainStackedWidget = QStackedWidget(self.MainWidget)
        self.MainStackedWidget.setObjectName(u"MainStackedWidget")
        self.MainStackedWidget.setGeometry(QRect(0, 80, 1131, 521))
        self.DashBoardPage = QWidget()
        self.DashBoardPage.setObjectName(u"DashBoardPage")
        self.frame = QFrame(self.DashBoardPage)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(40, 80, 181, 91))
        self.frame.setStyleSheet(u"background-color: #F0F0F0")
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.label_2 = QLabel(self.frame)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(30, 10, 91, 16))
        self.TotalUnits = QLabel(self.frame)
        self.TotalUnits.setObjectName(u"TotalUnits")
        self.TotalUnits.setGeometry(QRect(30, 50, 47, 14))
        self.frame_2 = QFrame(self.DashBoardPage)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(260, 80, 161, 91))
        self.frame_2.setStyleSheet(u"background-color: #F0F0F0")
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.label_3 = QLabel(self.frame_2)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(20, 10, 91, 16))
        self.TotalTenants = QLabel(self.frame_2)
        self.TotalTenants.setObjectName(u"TotalTenants")
        self.TotalTenants.setGeometry(QRect(20, 50, 47, 14))
        self.frame_3 = QFrame(self.DashBoardPage)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setGeometry(QRect(530, 80, 161, 91))
        self.frame_3.setStyleSheet(u"background-color: #F0F0F0")
        self.frame_3.setFrameShape(QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.label_4 = QLabel(self.frame_3)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 10, 91, 16))
        self.AvailableUnits = QLabel(self.frame_3)
        self.AvailableUnits.setObjectName(u"AvailableUnits")
        self.AvailableUnits.setGeometry(QRect(10, 50, 47, 14))
        self.frame_4 = QFrame(self.DashBoardPage)
        self.frame_4.setObjectName(u"frame_4")
        self.frame_4.setGeometry(QRect(870, 80, 161, 91))
        self.frame_4.setStyleSheet(u"background-color: #F0F0F0")
        self.frame_4.setFrameShape(QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QFrame.Raised)
        self.label_5 = QLabel(self.frame_4)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 10, 91, 16))
        self.label_6 = QLabel(self.frame_4)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(20, 40, 16, 21))
        self.TotalEarnings = QLabel(self.frame_4)
        self.TotalEarnings.setObjectName(u"TotalEarnings")
        self.TotalEarnings.setGeometry(QRect(50, 50, 47, 14))
        self.MainStackedWidget.addWidget(self.DashBoardPage)
        self.RentalsPage = QWidget()
        self.RentalsPage.setObjectName(u"RentalsPage")
        self.RentalsTable = QTableWidget(self.RentalsPage)
        if (self.RentalsTable.columnCount() < 4):
            self.RentalsTable.setColumnCount(4)
        __qtablewidgetitem = QTableWidgetItem()
        self.RentalsTable.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.RentalsTable.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        self.RentalsTable.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        __qtablewidgetitem3 = QTableWidgetItem()
        self.RentalsTable.setHorizontalHeaderItem(3, __qtablewidgetitem3)
        self.RentalsTable.setObjectName(u"RentalsTable")
        self.RentalsTable.setGeometry(QRect(0, 40, 841, 481))
        self.AddTenantFrame_2 = QFrame(self.RentalsPage)
        self.AddTenantFrame_2.setObjectName(u"AddTenantFrame_2")
        self.AddTenantFrame_2.setGeometry(QRect(840, 10, 291, 511))
        self.AddTenantFrame_2.setFrameShape(QFrame.StyledPanel)
        self.AddTenantFrame_2.setFrameShadow(QFrame.Raised)
        self.label_19 = QLabel(self.AddTenantFrame_2)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(130, 40, 71, 16))
        self.label_20 = QLabel(self.AddTenantFrame_2)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(20, 100, 71, 16))
        self.label_21 = QLabel(self.AddTenantFrame_2)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(20, 170, 51, 16))
        self.label_22 = QLabel(self.AddTenantFrame_2)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(20, 240, 81, 16))
        self.StartDate = QLineEdit(self.AddTenantFrame_2)
        self.StartDate.setObjectName(u"StartDate")
        self.StartDate.setGeometry(QRect(30, 270, 251, 20))
        self.label_23 = QLabel(self.AddTenantFrame_2)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(20, 310, 91, 16))
        self.ContactNum_2 = QLineEdit(self.AddTenantFrame_2)
        self.ContactNum_2.setObjectName(u"ContactNum_2")
        self.ContactNum_2.setGeometry(QRect(30, 340, 251, 20))
        self.AddRental = QPushButton(self.AddTenantFrame_2)
        self.AddRental.setObjectName(u"AddRental")
        self.AddRental.setGeometry(QRect(114, 420, 91, 23))
        self.UnitIDRentals = QComboBox(self.AddTenantFrame_2)
        self.UnitIDRentals.setObjectName(u"UnitIDRentals")
        self.UnitIDRentals.setGeometry(QRect(30, 120, 181, 22))
        self.TenantIDRentals = QComboBox(self.AddTenantFrame_2)
        self.TenantIDRentals.setObjectName(u"TenantIDRentals")
        self.TenantIDRentals.setGeometry(QRect(30, 190, 181, 22))
        self.SearchRentals = QPushButton(self.RentalsPage)
        self.SearchRentals.setObjectName(u"SearchRentals")
        self.SearchRentals.setGeometry(QRect(10, 0, 75, 23))
        self.SearchBarRentals = QLineEdit(self.RentalsPage)
        self.SearchBarRentals.setObjectName(u"SearchBarRentals")
        self.SearchBarRentals.setGeometry(QRect(100, 0, 251, 20))
        self.SearchRentalsComboBox = QComboBox(self.RentalsPage)
        self.SearchRentalsComboBox.addItem("")
        self.SearchRentalsComboBox.addItem("")
        self.SearchRentalsComboBox.addItem("")
        self.SearchRentalsComboBox.addItem("")
        self.SearchRentalsComboBox.setObjectName(u"SearchRentalsComboBox")
        self.SearchRentalsComboBox.setGeometry(QRect(390, 0, 101, 22))
        self.MainStackedWidget.addWidget(self.RentalsPage)
        self.PaymentsPage = QWidget()
        self.PaymentsPage.setObjectName(u"PaymentsPage")
        self.PaymentsTable = QTableWidget(self.PaymentsPage)
        if (self.PaymentsTable.columnCount() < 5):
            self.PaymentsTable.setColumnCount(5)
        __qtablewidgetitem4 = QTableWidgetItem()
        self.PaymentsTable.setHorizontalHeaderItem(0, __qtablewidgetitem4)
        __qtablewidgetitem5 = QTableWidgetItem()
        self.PaymentsTable.setHorizontalHeaderItem(1, __qtablewidgetitem5)
        __qtablewidgetitem6 = QTableWidgetItem()
        self.PaymentsTable.setHorizontalHeaderItem(2, __qtablewidgetitem6)
        __qtablewidgetitem7 = QTableWidgetItem()
        self.PaymentsTable.setHorizontalHeaderItem(3, __qtablewidgetitem7)
        __qtablewidgetitem8 = QTableWidgetItem()
        self.PaymentsTable.setHorizontalHeaderItem(4, __qtablewidgetitem8)
        self.PaymentsTable.setObjectName(u"PaymentsTable")
        self.PaymentsTable.setGeometry(QRect(0, 40, 841, 481))
        self.AddTenantFrame_3 = QFrame(self.PaymentsPage)
        self.AddTenantFrame_3.setObjectName(u"AddTenantFrame_3")
        self.AddTenantFrame_3.setGeometry(QRect(840, 10, 291, 511))
        self.AddTenantFrame_3.setFrameShape(QFrame.StyledPanel)
        self.AddTenantFrame_3.setFrameShadow(QFrame.Raised)
        self.label_24 = QLabel(self.AddTenantFrame_3)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(130, 40, 81, 16))
        self.label_25 = QLabel(self.AddTenantFrame_3)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(20, 90, 71, 16))
        self.label_26 = QLabel(self.AddTenantFrame_3)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(20, 160, 51, 16))
        self.label_27 = QLabel(self.AddTenantFrame_3)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(20, 220, 81, 16))
        self.PaymentDate = QLineEdit(self.AddTenantFrame_3)
        self.PaymentDate.setObjectName(u"PaymentDate")
        self.PaymentDate.setGeometry(QRect(30, 240, 251, 20))
        self.label_28 = QLabel(self.AddTenantFrame_3)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(20, 280, 91, 16))
        self.PaymentType = QLineEdit(self.AddTenantFrame_3)
        self.PaymentType.setObjectName(u"PaymentType")
        self.PaymentType.setGeometry(QRect(30, 300, 141, 20))
        self.AddPayment = QPushButton(self.AddTenantFrame_3)
        self.AddPayment.setObjectName(u"AddPayment")
        self.AddPayment.setGeometry(QRect(114, 420, 91, 23))
        self.label_29 = QLabel(self.AddTenantFrame_3)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(20, 340, 91, 16))
        self.PaymentStatus = QLineEdit(self.AddTenantFrame_3)
        self.PaymentStatus.setObjectName(u"PaymentStatus")
        self.PaymentStatus.setGeometry(QRect(30, 360, 113, 20))
        self.UnitIDPayments = QComboBox(self.AddTenantFrame_3)
        self.UnitIDPayments.setObjectName(u"UnitIDPayments")
        self.UnitIDPayments.setGeometry(QRect(30, 110, 181, 22))
        self.TenantIDPayments = QComboBox(self.AddTenantFrame_3)
        self.TenantIDPayments.setObjectName(u"TenantIDPayments")
        self.TenantIDPayments.setGeometry(QRect(30, 180, 181, 22))
        self.SearchPayments = QPushButton(self.PaymentsPage)
        self.SearchPayments.setObjectName(u"SearchPayments")
        self.SearchPayments.setGeometry(QRect(10, 0, 75, 23))
        self.SearchBarPayments = QLineEdit(self.PaymentsPage)
        self.SearchBarPayments.setObjectName(u"SearchBarPayments")
        self.SearchBarPayments.setGeometry(QRect(100, 0, 251, 20))
        self.SearchPaymentsComboBox = QComboBox(self.PaymentsPage)
        self.SearchPaymentsComboBox.addItem("")
        self.SearchPaymentsComboBox.addItem("")
        self.SearchPaymentsComboBox.addItem("")
        self.SearchPaymentsComboBox.addItem("")
        self.SearchPaymentsComboBox.setObjectName(u"SearchPaymentsComboBox")
        self.SearchPaymentsComboBox.setGeometry(QRect(390, 0, 101, 22))
        self.MainStackedWidget.addWidget(self.PaymentsPage)
        self.TenantsPage = QWidget()
        self.TenantsPage.setObjectName(u"TenantsPage")
        self.TenantsTable = QTableWidget(self.TenantsPage)
        if (self.TenantsTable.columnCount() < 4):
            self.TenantsTable.setColumnCount(4)
        __qtablewidgetitem9 = QTableWidgetItem()
        self.TenantsTable.setHorizontalHeaderItem(0, __qtablewidgetitem9)
        __qtablewidgetitem10 = QTableWidgetItem()
        self.TenantsTable.setHorizontalHeaderItem(1, __qtablewidgetitem10)
        __qtablewidgetitem11 = QTableWidgetItem()
        self.TenantsTable.setHorizontalHeaderItem(2, __qtablewidgetitem11)
        __qtablewidgetitem12 = QTableWidgetItem()
        self.TenantsTable.setHorizontalHeaderItem(3, __qtablewidgetitem12)
        self.TenantsTable.setObjectName(u"TenantsTable")
        self.TenantsTable.setGeometry(QRect(0, 40, 841, 481))
        self.AddTenantFrame = QFrame(self.TenantsPage)
        self.AddTenantFrame.setObjectName(u"AddTenantFrame")
        self.AddTenantFrame.setGeometry(QRect(840, 10, 291, 511))
        self.AddTenantFrame.setFrameShape(QFrame.StyledPanel)
        self.AddTenantFrame.setFrameShadow(QFrame.Raised)
        self.label_7 = QLabel(self.AddTenantFrame)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(130, 40, 71, 16))
        self.label_8 = QLabel(self.AddTenantFrame)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(20, 100, 71, 16))
        self.TenantName = QLineEdit(self.AddTenantFrame)
        self.TenantName.setObjectName(u"TenantName")
        self.TenantName.setGeometry(QRect(30, 120, 241, 21))
        self.TenantID = QLineEdit(self.AddTenantFrame)
        self.TenantID.setObjectName(u"TenantID")
        self.TenantID.setGeometry(QRect(30, 190, 151, 20))
        self.label_9 = QLabel(self.AddTenantFrame)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(20, 170, 51, 16))
        self.label_10 = QLabel(self.AddTenantFrame)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(20, 240, 81, 16))
        self.EmailAdd = QLineEdit(self.AddTenantFrame)
        self.EmailAdd.setObjectName(u"EmailAdd")
        self.EmailAdd.setGeometry(QRect(30, 270, 251, 20))
        self.label_11 = QLabel(self.AddTenantFrame)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(20, 310, 91, 16))
        self.ContactNum = QLineEdit(self.AddTenantFrame)
        self.ContactNum.setObjectName(u"ContactNum")
        self.ContactNum.setGeometry(QRect(60, 340, 221, 20))
        self.label_12 = QLabel(self.AddTenantFrame)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(30, 340, 21, 16))
        self.AddTenant = QPushButton(self.AddTenantFrame)
        self.AddTenant.setObjectName(u"AddTenant")
        self.AddTenant.setGeometry(QRect(114, 420, 91, 23))
        self.SearchTenant = QPushButton(self.TenantsPage)
        self.SearchTenant.setObjectName(u"SearchTenant")
        self.SearchTenant.setGeometry(QRect(10, 0, 75, 23))
        self.SearchBarTenants = QLineEdit(self.TenantsPage)
        self.SearchBarTenants.setObjectName(u"SearchBarTenants")
        self.SearchBarTenants.setGeometry(QRect(100, 0, 251, 20))
        self.SearchTenantComboBox = QComboBox(self.TenantsPage)
        self.SearchTenantComboBox.addItem("")
        self.SearchTenantComboBox.addItem("")
        self.SearchTenantComboBox.setObjectName(u"SearchTenantComboBox")
        self.SearchTenantComboBox.setGeometry(QRect(390, 0, 101, 22))
        self.MainStackedWidget.addWidget(self.TenantsPage)
        self.UnitsPage = QWidget()
        self.UnitsPage.setObjectName(u"UnitsPage")
        self.UnitsTable = QTableWidget(self.UnitsPage)
        if (self.UnitsTable.columnCount() < 5):
            self.UnitsTable.setColumnCount(5)
        __qtablewidgetitem13 = QTableWidgetItem()
        self.UnitsTable.setHorizontalHeaderItem(0, __qtablewidgetitem13)
        __qtablewidgetitem14 = QTableWidgetItem()
        self.UnitsTable.setHorizontalHeaderItem(1, __qtablewidgetitem14)
        __qtablewidgetitem15 = QTableWidgetItem()
        self.UnitsTable.setHorizontalHeaderItem(2, __qtablewidgetitem15)
        __qtablewidgetitem16 = QTableWidgetItem()
        self.UnitsTable.setHorizontalHeaderItem(3, __qtablewidgetitem16)
        __qtablewidgetitem17 = QTableWidgetItem()
        self.UnitsTable.setHorizontalHeaderItem(4, __qtablewidgetitem17)
        self.UnitsTable.setObjectName(u"UnitsTable")
        self.UnitsTable.setGeometry(QRect(0, 40, 841, 481))
        self.AddUnitFrame = QFrame(self.UnitsPage)
        self.AddUnitFrame.setObjectName(u"AddUnitFrame")
        self.AddUnitFrame.setGeometry(QRect(840, 10, 291, 501))
        self.AddUnitFrame.setFrameShape(QFrame.StyledPanel)
        self.AddUnitFrame.setFrameShadow(QFrame.Raised)
        self.label_13 = QLabel(self.AddUnitFrame)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(130, 40, 71, 16))
        self.label_14 = QLabel(self.AddUnitFrame)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(20, 100, 71, 16))
        self.UnitName = QLineEdit(self.AddUnitFrame)
        self.UnitName.setObjectName(u"UnitName")
        self.UnitName.setGeometry(QRect(30, 120, 241, 21))
        self.UnitID = QLineEdit(self.AddUnitFrame)
        self.UnitID.setObjectName(u"UnitID")
        self.UnitID.setGeometry(QRect(30, 190, 151, 20))
        self.label_15 = QLabel(self.AddUnitFrame)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(20, 170, 51, 16))
        self.label_16 = QLabel(self.AddUnitFrame)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(20, 240, 61, 16))
        self.StoreType = QLineEdit(self.AddUnitFrame)
        self.StoreType.setObjectName(u"StoreType")
        self.StoreType.setGeometry(QRect(30, 270, 251, 20))
        self.label_17 = QLabel(self.AddUnitFrame)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(20, 310, 61, 16))
        self.UnitPrice = QLineEdit(self.AddUnitFrame)
        self.UnitPrice.setObjectName(u"UnitPrice")
        self.UnitPrice.setGeometry(QRect(40, 340, 241, 20))
        self.label_18 = QLabel(self.AddUnitFrame)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(30, 340, 16, 16))
        self.AddUnit = QPushButton(self.AddUnitFrame)
        self.AddUnit.setObjectName(u"AddUnit")
        self.AddUnit.setGeometry(QRect(114, 420, 91, 23))
        self.SearchUnit = QPushButton(self.UnitsPage)
        self.SearchUnit.setObjectName(u"SearchUnit")
        self.SearchUnit.setGeometry(QRect(10, 0, 75, 23))
        self.SearchBarUnit = QLineEdit(self.UnitsPage)
        self.SearchBarUnit.setObjectName(u"SearchBarUnit")
        self.SearchBarUnit.setGeometry(QRect(100, 0, 251, 20))
        self.SearchUnitComboBox = QComboBox(self.UnitsPage)
        self.SearchUnitComboBox.addItem("")
        self.SearchUnitComboBox.addItem("")
        self.SearchUnitComboBox.setObjectName(u"SearchUnitComboBox")
        self.SearchUnitComboBox.setGeometry(QRect(390, 0, 101, 22))
        self.MainStackedWidget.addWidget(self.UnitsPage)
        self.DashBoardFrame = QFrame(self.MainWidget)
        self.DashBoardFrame.setObjectName(u"DashBoardFrame")
        self.DashBoardFrame.setGeometry(QRect(0, 0, 1131, 81))
        self.DashBoardFrame.setFrameShape(QFrame.StyledPanel)
        self.DashBoardFrame.setFrameShadow(QFrame.Raised)
        self.DashBoardHolderFrame = QFrame(self.DashBoardFrame)
        self.DashBoardHolderFrame.setObjectName(u"DashBoardHolderFrame")
        self.DashBoardHolderFrame.setGeometry(QRect(0, 20, 1131, 41))
        self.DashBoardHolderFrame.setStyleSheet(u"background-color: #31302E")
        self.DashBoardHolderFrame.setFrameShape(QFrame.StyledPanel)
        self.DashBoardHolderFrame.setFrameShadow(QFrame.Raised)
        self.DashboardButton = QPushButton(self.DashBoardHolderFrame)
        self.DashboardButton.setObjectName(u"DashboardButton")
        self.DashboardButton.setGeometry(QRect(30, 10, 75, 23))
        self.DashboardButton.setStyleSheet(u"background-color: #F0F0F0")
        self.TenantsButton = QPushButton(self.DashBoardHolderFrame)
        self.TenantsButton.setObjectName(u"TenantsButton")
        self.TenantsButton.setGeometry(QRect(180, 10, 75, 23))
        self.UnitsButton = QPushButton(self.DashBoardHolderFrame)
        self.UnitsButton.setObjectName(u"UnitsButton")
        self.UnitsButton.setGeometry(QRect(270, 10, 75, 23))
        self.RentalsButton = QPushButton(self.DashBoardHolderFrame)
        self.RentalsButton.setObjectName(u"RentalsButton")
        self.RentalsButton.setGeometry(QRect(360, 10, 75, 23))
        self.PaymentsButton = QPushButton(self.DashBoardHolderFrame)
        self.PaymentsButton.setObjectName(u"PaymentsButton")
        self.PaymentsButton.setGeometry(QRect(450, 10, 75, 23))
        self.label = QLabel(self.DashBoardHolderFrame)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(880, 10, 201, 20))
        self.label.setStyleSheet(u"color: #FFFFFF")
        self.LoginStackedWidget.addWidget(self.MainWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        self.LoginStackedWidget.setCurrentIndex(0)
        self.MainStackedWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label_30.setText("")
        self.label_31.setText("")
        self.label_32.setText("")
        self.label_33.setText(QCoreApplication.translate("MainWindow", u"Log In", None))
        self.lineEdit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Enter Username", None))
        self.lineEdit_2.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Enter Password", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"L o g  I n", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"TOTAL UNITS", None))
        self.TotalUnits.setText(QCoreApplication.translate("MainWindow", u"76", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"TOTAL TENANTS", None))
        self.TotalTenants.setText(QCoreApplication.translate("MainWindow", u"24", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"AVAILABLE UNITS", None))
        self.AvailableUnits.setText(QCoreApplication.translate("MainWindow", u"43", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"TOTAL EARNINGS", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"\u20b1", None))
        self.TotalEarnings.setText(QCoreApplication.translate("MainWindow", u"50,000", None))
        ___qtablewidgetitem = self.RentalsTable.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("MainWindow", u"UnitID", None));
        ___qtablewidgetitem1 = self.RentalsTable.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("MainWindow", u"TenantID", None));
        ___qtablewidgetitem2 = self.RentalsTable.horizontalHeaderItem(2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("MainWindow", u"StartDate", None));
        ___qtablewidgetitem3 = self.RentalsTable.horizontalHeaderItem(3)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("MainWindow", u"EndDate", None));
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"ADD RENTALS", None))
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"Unit ID:", None))
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"Tenant ID:", None))
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"Start Date:", None))
        self.StartDate.setPlaceholderText(QCoreApplication.translate("MainWindow", u"YYYY/MM/DD", None))
        self.label_23.setText(QCoreApplication.translate("MainWindow", u"End Date:", None))
        self.ContactNum_2.setPlaceholderText(QCoreApplication.translate("MainWindow", u"YYYY/MM/DD", None))
        self.AddRental.setText(QCoreApplication.translate("MainWindow", u"Add", None))
        self.SearchRentals.setText(QCoreApplication.translate("MainWindow", u"Search", None))
        self.SearchRentalsComboBox.setItemText(0, QCoreApplication.translate("MainWindow", u"Tenant Name", None))
        self.SearchRentalsComboBox.setItemText(1, QCoreApplication.translate("MainWindow", u"Unit Name", None))
        self.SearchRentalsComboBox.setItemText(2, QCoreApplication.translate("MainWindow", u"Unit ID", None))
        self.SearchRentalsComboBox.setItemText(3, QCoreApplication.translate("MainWindow", u"Tenant ID", None))

        ___qtablewidgetitem4 = self.PaymentsTable.horizontalHeaderItem(0)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("MainWindow", u"UnitID", None));
        ___qtablewidgetitem5 = self.PaymentsTable.horizontalHeaderItem(1)
        ___qtablewidgetitem5.setText(QCoreApplication.translate("MainWindow", u"TenantID", None));
        ___qtablewidgetitem6 = self.PaymentsTable.horizontalHeaderItem(2)
        ___qtablewidgetitem6.setText(QCoreApplication.translate("MainWindow", u"PaymentDate", None));
        ___qtablewidgetitem7 = self.PaymentsTable.horizontalHeaderItem(3)
        ___qtablewidgetitem7.setText(QCoreApplication.translate("MainWindow", u"PaymentType", None));
        ___qtablewidgetitem8 = self.PaymentsTable.horizontalHeaderItem(4)
        ___qtablewidgetitem8.setText(QCoreApplication.translate("MainWindow", u"PaymentStatus", None));
        self.label_24.setText(QCoreApplication.translate("MainWindow", u"ADD PAYMENT", None))
        self.label_25.setText(QCoreApplication.translate("MainWindow", u"Unit ID:", None))
        self.label_26.setText(QCoreApplication.translate("MainWindow", u"Tenant ID:", None))
        self.label_27.setText(QCoreApplication.translate("MainWindow", u"Payment Date:", None))
        self.PaymentDate.setPlaceholderText(QCoreApplication.translate("MainWindow", u"YYYY/MM/DD", None))
        self.label_28.setText(QCoreApplication.translate("MainWindow", u"Payment Type:", None))
        self.PaymentType.setPlaceholderText("")
        self.AddPayment.setText(QCoreApplication.translate("MainWindow", u"Add", None))
        self.label_29.setText(QCoreApplication.translate("MainWindow", u"Payment Status:", None))
        self.SearchPayments.setText(QCoreApplication.translate("MainWindow", u"Search", None))
        self.SearchPaymentsComboBox.setItemText(0, QCoreApplication.translate("MainWindow", u"Tenant Name", None))
        self.SearchPaymentsComboBox.setItemText(1, QCoreApplication.translate("MainWindow", u"Unit Name", None))
        self.SearchPaymentsComboBox.setItemText(2, QCoreApplication.translate("MainWindow", u"Unit ID", None))
        self.SearchPaymentsComboBox.setItemText(3, QCoreApplication.translate("MainWindow", u"Tenant ID", None))

        ___qtablewidgetitem9 = self.TenantsTable.horizontalHeaderItem(0)
        ___qtablewidgetitem9.setText(QCoreApplication.translate("MainWindow", u"TenantID", None));
        ___qtablewidgetitem10 = self.TenantsTable.horizontalHeaderItem(1)
        ___qtablewidgetitem10.setText(QCoreApplication.translate("MainWindow", u"TenantName", None));
        ___qtablewidgetitem11 = self.TenantsTable.horizontalHeaderItem(2)
        ___qtablewidgetitem11.setText(QCoreApplication.translate("MainWindow", u"EmailAddress", None));
        ___qtablewidgetitem12 = self.TenantsTable.horizontalHeaderItem(3)
        ___qtablewidgetitem12.setText(QCoreApplication.translate("MainWindow", u"ContactNumber", None));
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"ADD TENANT", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Tenant Name:", None))
#if QT_CONFIG(tooltip)
        self.TenantID.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.TenantID.setPlaceholderText(QCoreApplication.translate("MainWindow", u"XXXX-XXXX", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Tenant ID:", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Email Address:", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Contact Number:", None))
        self.ContactNum.setPlaceholderText(QCoreApplication.translate("MainWindow", u"000 0000 000", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"+63", None))
        self.AddTenant.setText(QCoreApplication.translate("MainWindow", u"Add", None))
        self.SearchTenant.setText(QCoreApplication.translate("MainWindow", u"Search", None))
        self.SearchTenantComboBox.setItemText(0, QCoreApplication.translate("MainWindow", u"Tenant Name", None))
        self.SearchTenantComboBox.setItemText(1, QCoreApplication.translate("MainWindow", u"Tenant ID", None))

        ___qtablewidgetitem13 = self.UnitsTable.horizontalHeaderItem(0)
        ___qtablewidgetitem13.setText(QCoreApplication.translate("MainWindow", u"UnitID", None));
        ___qtablewidgetitem14 = self.UnitsTable.horizontalHeaderItem(1)
        ___qtablewidgetitem14.setText(QCoreApplication.translate("MainWindow", u"UnitName", None));
        ___qtablewidgetitem15 = self.UnitsTable.horizontalHeaderItem(2)
        ___qtablewidgetitem15.setText(QCoreApplication.translate("MainWindow", u"StoreType", None));
        ___qtablewidgetitem16 = self.UnitsTable.horizontalHeaderItem(3)
        ___qtablewidgetitem16.setText(QCoreApplication.translate("MainWindow", u"UnitStatus", None));
        ___qtablewidgetitem17 = self.UnitsTable.horizontalHeaderItem(4)
        ___qtablewidgetitem17.setText(QCoreApplication.translate("MainWindow", u"UnitPrice", None));
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"ADD UNIT", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Unit Name:", None))
#if QT_CONFIG(tooltip)
        self.UnitID.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.UnitID.setPlaceholderText(QCoreApplication.translate("MainWindow", u"XXX-XXXX", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"Unit ID:", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"Store Type:", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"Unit Price:", None))
        self.UnitPrice.setPlaceholderText("")
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"\u20b1", None))
        self.AddUnit.setText(QCoreApplication.translate("MainWindow", u"Add", None))
        self.SearchUnit.setText(QCoreApplication.translate("MainWindow", u"Search", None))
        self.SearchUnitComboBox.setItemText(0, QCoreApplication.translate("MainWindow", u"Unit Name", None))
        self.SearchUnitComboBox.setItemText(1, QCoreApplication.translate("MainWindow", u"Unit ID", None))

        self.DashboardButton.setText(QCoreApplication.translate("MainWindow", u"DASHBOARD", None))
        self.TenantsButton.setText(QCoreApplication.translate("MainWindow", u"TENANTS", None))
        self.UnitsButton.setText(QCoreApplication.translate("MainWindow", u"UNITS", None))
        self.RentalsButton.setText(QCoreApplication.translate("MainWindow", u"RENTALS", None))
        self.PaymentsButton.setText(QCoreApplication.translate("MainWindow", u"PAYMENTS", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"STORE RENTAL MANAGEMENT SYSTEM", None))
    # retranslateUi

